In [1]:
import numpy as np
import pandas as pd

/home/user01/.local/lib/python3.8/site-packages/pandas/core/computation/expressions.py:20: UserWarning: Pandas requires version '2.7.3' or newer of 'numexpr' (version '2.7.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [2]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [3]:
flats = pd.read_csv('flats_cleaned.csv')
houses = pd.read_csv('house_cleaned.csv')
df = pd.concat([flats,houses],ignore_index=True)
df = df.sample(df.shape[0],ignore_index=True)

In [4]:
df.sample(5)

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
2312,2 BHK Flat in Sector 92 Gurgaon,flat,signature global city 92,0.78,11142.0,700.0,Super Built up area 1010(93.83 sq.m.)Carpet ar...,2,2,3,others,"Sector 92 Gurgaon, Gurgaon, Haryana",2.0,NaN,Aug 2025,"['Iris Broadway Mall', 'Pataudi Road', 'Dwarka...",Under construction flat for sale in signature ...,"['4 Fan', '4 Light', '3 AC', '1 Modular Kitche...","['Lift(s)', 'Swimming Pool', 'Park', 'Fitness ...","['Environment5 out of 5', 'Safety3 out of 5', ..."
1424,2 BHK Flat in Nirvana Country,flat,unitech fresco,1.14,8532.0,1336.0,Super Built up area 1336(124.12 sq.m.)Built Up...,2,2,2,others,"1902, Nirvana Country, Gurgaon, Haryana",19.0,East,5 to 10 Year Old,"['Rapid Metro Station Sector 55 56', 'M3M Cosm...","Situated in nirvana country, gurgaon, unitech ...","['4 Fan', '1 Exhaust Fan', '1 Dining Table', '...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction3 out of..."
1889,4 BHK Flat in Sector 112 Gurgaon,flat,experion windchants,5.31,11204.0,4739.0,Super Built up area 4739(440.27 sq.m.)Built Up...,4,6,3+,"pooja room,servant room","Sector 112 Gurgaon, Gurgaon, Haryana",15.0,South,1 to 5 Year Old,"['Ansal Plaza', 'Dwaraka Expressway', 'First S...",Huge 4 bhk servant in the most demanded societ...,"['7 AC', 'No Bed', 'No Chimney', 'No Curtains'...","['Power Back-up', 'Feng Shui / Vaastu Complian...","['Green Area5 out of 5', 'Construction5 out of..."
1529,3 BHK Flat in Sector 95 Gurgaon,flat,sidhartha ncr one phase,0.90,4500.0,2000.0,Built Up area: 2000 (185.81 sq.m.),3,3,1,not available,"Sector 95 Gurgaon, Gurgaon, Haryana",15.0,NaN,1 to 5 Year Old,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",Residential apartment for sell.Located on 15th...,"['1 Wardrobe', '1 Fan', '1 Light', 'No AC', 'N...","['Power Back-up', 'Lift(s)', 'Swimming Pool', ...","['Management4 out of 5', 'Green Area4 out of 5..."
2915,5 Bedroom House for sale in Sector 14 Gurgaon,house,independent,6.46,18889.0,3420.0,Plot area 380(317.73 sq.m.)Built Up area: 380 ...,5,5,2,"pooja room,study room,servant room","0001725, Sector 14 Gurgaon, Gurgaon, Haryana",3.0,East,5 to 10 Year Old,"['Sheetla Mata Mandir', 'Hsbc bank ATM', 'Hdfc...",House for sale plot size 380 sqyard 2 story ho...,"['5 Wardrobe', '10 Fan', '1 Exhaust Fan', '6 G...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment4 out of 5', 'Safety4 out of 5', ..."

In [5]:
df.shape

(3961, 20)

In [6]:
df.duplicated().sum()

0

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3961 entries, 0 to 3960
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3961 non-null   object
 1   property_type    3961 non-null   object
 2   society          3960 non-null   object
 3   price            3941 non-null   float64
 4   price_per_sqft   3941 non-null   float64
 5   area             3941 non-null   float64
 6   areaWithType     3961 non-null   object
 7   bedRoom          3961 non-null   int64
 8   bathroom         3961 non-null   int64
 9   balcony          3961 non-null   object
 10  additionalRoom   3961 non-null   object
 11  address          3950 non-null   object
 12  floorNum         3940 non-null   float64
 13  facing           2784 non-null   object
 14  agePossession    3960 non-null   object
 15  nearbyLocations  3754 non-null   object
 16  description      3961 non-null   object
 17  furnishDetails   2929 non-null   object
 18  features         3252 non-null   object
 19  rating           3511 non-null   object
dtypes: float64(4), int64(2), object(14)
memory usage: 619.0+ KB

In [8]:
df.isnull().sum()

property_name         0
property_type         0
society               1
price                20
price_per_sqft       20
area                 20
areaWithType          0
bedRoom               0
bathroom              0
balcony               0
additionalRoom        0
address              11
floorNum             21
facing             1177
agePossession         1
nearbyLocations     207
description           0
furnishDetails     1032
features            709
rating              450
dtype: int64

In [9]:
df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Sohna,flat,ashiana anmol,0.88,11125.0,791.0,Super Built up area 1275(118.45 sq.m.)Carpet a...,2,2,2,not available,"Sohna, Gurgaon, Haryana",13.0,East,1 to 5 Year Old,"['Global Signum Plaza', 'Airia Mall', 'Sohna R...",Fully furnished flat with southfacing balconie...,"['1 Water Purifier', '4 Fan', '1 Exhaust Fan',...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area4 out of 5', 'Amenities4 out of 5'..."
1,3 BHK Flat in Sector 70 Gurgaon,flat,shree vardhman victoria,1.65,8461.0,1950.0,Super Built up area 1950(181.16 sq.m.)Carpet a...,3,4,3,servant room,"Sector 70 Gurgaon, Gurgaon, Haryana",1.0,North,1 to 5 Year Old,"['Airia Mall', 'Golf Course Extn Road', 'Sohna...",Victoria is a perfect residential complex from...,"['1 Water Purifier', '4 Fan', '1 Fridge', '1 D...","['Water purifier', 'Centrally Air Conditioned'...","['Green Area5 out of 5', 'Construction5 out of..."
2,3 BHK Flat in Sector 37D Gurgaon,flat,bptp terra,1.45,8006.0,1811.0,Super Built up area 1811(168.25 sq.m.)Built Up...,3,3,3,not available,"803, Sector 37D Gurgaon, Gurgaon, Haryana",8.0,South-East,1 to 5 Year Old,"['Airia Mall', 'Dwarka Expressway', 'Golf Cour...",This lovely 3 bhk apartment/flat in sector 37d...,"['5 AC', '1 Chimney', '1 Modular Kitchen', '2 ...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area4.5 out of 5', 'Construction4.5 ou..."
3,3 BHK Flat in Sector 72 Gurgaon,flat,tata primanti,3.30,15384.0,2145.0,Super Built up area 2145(199.28 sq.m.)Built Up...,3,3,3+,servant room,"1001, Sector 72 Gurgaon, Gurgaon, Haryana",10.0,North-East,1 to 5 Year Old,"['Sector 55-56 Metro Station', 'Omaxe City Cen...",Check out this 3 bhk apartment for sale in tat...,"['3 Wardrobe', '7 Fan', '1 Exhaust Fan', '4 Ge...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area4 out of 5', 'Construction4 out of..."
4,2 BHK Flat in Sector 107 Gurgaon,flat,signature global solera,0.28,5828.0,480.0,Carpet area: 489 (45.43 sq.m.),2,2,2,not available,"Sector 107 Gurgaon, Gurgaon, Haryana",0.0,North-East,1 to 5 Year Old,"['Gurgaon Dreamz Mall', 'Dwarka Expressway', ""...",This lovely 2 bhk apartment/flat in sector-107...,"['1 Wardrobe', '2 Fan', '1 Exhaust Fan', '2 Li...","['Security / Fire Alarm', 'Intercom Facility',...","['Green Area4.5 out of 5', 'Construction4.5 ou..."

In [10]:
df.insert(loc=3,column='sector',value=df['property_name'].str.split('in').str.get(1).str.replace('Gurgaon','').str.strip())

In [11]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Sohna,flat,ashiana anmol,Sohna,0.88,11125.0,791.0,Super Built up area 1275(118.45 sq.m.)Carpet a...,2,2,2,not available,"Sohna, Gurgaon, Haryana",13.0,East,1 to 5 Year Old,"['Global Signum Plaza', 'Airia Mall', 'Sohna R...",Fully furnished flat with southfacing balconie...,"['1 Water Purifier', '4 Fan', '1 Exhaust Fan',...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area4 out of 5', 'Amenities4 out of 5'..."
1,3 BHK Flat in Sector 70 Gurgaon,flat,shree vardhman victoria,Sector 70,1.65,8461.0,1950.0,Super Built up area 1950(181.16 sq.m.)Carpet a...,3,4,3,servant room,"Sector 70 Gurgaon, Gurgaon, Haryana",1.0,North,1 to 5 Year Old,"['Airia Mall', 'Golf Course Extn Road', 'Sohna...",Victoria is a perfect residential complex from...,"['1 Water Purifier', '4 Fan', '1 Fridge', '1 D...","['Water purifier', 'Centrally Air Conditioned'...","['Green Area5 out of 5', 'Construction5 out of..."
2,3 BHK Flat in Sector 37D Gurgaon,flat,bptp terra,Sector 37D,1.45,8006.0,1811.0,Super Built up area 1811(168.25 sq.m.)Built Up...,3,3,3,not available,"803, Sector 37D Gurgaon, Gurgaon, Haryana",8.0,South-East,1 to 5 Year Old,"['Airia Mall', 'Dwarka Expressway', 'Golf Cour...",This lovely 3 bhk apartment/flat in sector 37d...,"['5 AC', '1 Chimney', '1 Modular Kitchen', '2 ...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area4.5 out of 5', 'Construction4.5 ou..."
3,3 BHK Flat in Sector 72 Gurgaon,flat,tata primanti,Sector 72,3.30,15384.0,2145.0,Super Built up area 2145(199.28 sq.m.)Built Up...,3,3,3+,servant room,"1001, Sector 72 Gurgaon, Gurgaon, Haryana",10.0,North-East,1 to 5 Year Old,"['Sector 55-56 Metro Station', 'Omaxe City Cen...",Check out this 3 bhk apartment for sale in tat...,"['3 Wardrobe', '7 Fan', '1 Exhaust Fan', '4 Ge...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area4 out of 5', 'Construction4 out of..."
4,2 BHK Flat in Sector 107 Gurgaon,flat,signature global solera,Sector 107,0.28,5828.0,480.0,Carpet area: 489 (45.43 sq.m.),2,2,2,not available,"Sector 107 Gurgaon, Gurgaon, Haryana",0.0,North-East,1 to 5 Year Old,"['Gurgaon Dreamz Mall', 'Dwarka Expressway', ""...",This lovely 2 bhk apartment/flat in sector-107...,"['1 Wardrobe', '2 Fan', '1 Exhaust Fan', '2 Li...","['Security / Fire Alarm', 'Intercom Facility',...","['Green Area4.5 out of 5', 'Construction4.5 ou..."

In [12]:
df['sector'] = df['sector'].str.lower()

In [13]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Sohna,flat,ashiana anmol,sohna,0.88,11125.0,791.0,Super Built up area 1275(118.45 sq.m.)Carpet a...,2,2,2,not available,"Sohna, Gurgaon, Haryana",13.0,East,1 to 5 Year Old,"['Global Signum Plaza', 'Airia Mall', 'Sohna R...",Fully furnished flat with southfacing balconie...,"['1 Water Purifier', '4 Fan', '1 Exhaust Fan',...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area4 out of 5', 'Amenities4 out of 5'..."
1,3 BHK Flat in Sector 70 Gurgaon,flat,shree vardhman victoria,sector 70,1.65,8461.0,1950.0,Super Built up area 1950(181.16 sq.m.)Carpet a...,3,4,3,servant room,"Sector 70 Gurgaon, Gurgaon, Haryana",1.0,North,1 to 5 Year Old,"['Airia Mall', 'Golf Course Extn Road', 'Sohna...",Victoria is a perfect residential complex from...,"['1 Water Purifier', '4 Fan', '1 Fridge', '1 D...","['Water purifier', 'Centrally Air Conditioned'...","['Green Area5 out of 5', 'Construction5 out of..."
2,3 BHK Flat in Sector 37D Gurgaon,flat,bptp terra,sector 37d,1.45,8006.0,1811.0,Super Built up area 1811(168.25 sq.m.)Built Up...,3,3,3,not available,"803, Sector 37D Gurgaon, Gurgaon, Haryana",8.0,South-East,1 to 5 Year Old,"['Airia Mall', 'Dwarka Expressway', 'Golf Cour...",This lovely 3 bhk apartment/flat in sector 37d...,"['5 AC', '1 Chimney', '1 Modular Kitchen', '2 ...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area4.5 out of 5', 'Construction4.5 ou..."
3,3 BHK Flat in Sector 72 Gurgaon,flat,tata primanti,sector 72,3.30,15384.0,2145.0,Super Built up area 2145(199.28 sq.m.)Built Up...,3,3,3+,servant room,"1001, Sector 72 Gurgaon, Gurgaon, Haryana",10.0,North-East,1 to 5 Year Old,"['Sector 55-56 Metro Station', 'Omaxe City Cen...",Check out this 3 bhk apartment for sale in tat...,"['3 Wardrobe', '7 Fan', '1 Exhaust Fan', '4 Ge...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area4 out of 5', 'Construction4 out of..."
4,2 BHK Flat in Sector 107 Gurgaon,flat,signature global solera,sector 107,0.28,5828.0,480.0,Carpet area: 489 (45.43 sq.m.),2,2,2,not available,"Sector 107 Gurgaon, Gurgaon, Haryana",0.0,North-East,1 to 5 Year Old,"['Gurgaon Dreamz Mall', 'Dwarka Expressway', ""...",This lovely 2 bhk apartment/flat in sector-107...,"['1 Wardrobe', '2 Fan', '1 Exhaust Fan', '2 Li...","['Security / Fire Alarm', 'Intercom Facility',...","['Green Area4.5 out of 5', 'Construction4.5 ou..."

In [14]:
df['sector'].value_counts()

sohna                                                        163
sector 102                                                   113
sector 85                                                    110
sector 92                                                    104
sector 69                                                     94
sector 81                                                     90
sector 65                                                     90
sector 90                                                     90
sector 109                                                    88
sector 79                                                     80
sector 83                                                     69
sector 37d                                                    68
sector 86                                                     67
sector 104                                                    66
sector 107                                                    60
sector 108                                                    59
sector 56                                                     57
sector 95                                                     57
sector 48                                                     56
sector 89                                                     56
sector 70a                                                    54
nirvana country                                               53
sector 37c                                                    53
sector 70                                                     53
sector 84                                                     51
sector-33 sohna                                               51
palam vihar                                                   50
sector 67                                                     48
sector 66                                                     46
sector 103                                                    45
sector 113                                                    43
dlf phase 2                                                   43
dlf phase 1                                                   43
sector 61                                                     42
sector 82                                                     42
sector 106                                                    38
sector 49                                                     36
sector 99a                                                    32
sushant lok phase 1                                           31
sector 68                                                     30
sector 77                                                     29
sector 72                                                     29
laxman vihar                                                  27
sector 71                                                     27
sector 54                                                     27
dlf phase 4                                                   26
sector 112                                                    24
sector 33                                                     23
sector 88a                                                    23
sector 111                                                    22
dlf phase 3                                                   22
sector 67a                                                    22
sector 22                                                     20
sector 82a                                                    20
sector 78                                                     19
sector 74                                                     18
sector 63a                                                    18
sector 62                                                     17
sector 91                                                     17
sushant lok phase 3                                           16
sector 99                                                     16
sector 110                                                    16
sector 63                                                     15
sector 60                                                     15
sector 14                                                     15
sector 76                                                     14
gwal pahari                                                   14
sector 3                                                      14
sector 53                                                     14
rajendra park                                                 14
sector 52                                                     14
sector 1 imt manesar                                          14
dlf phase 5                                                   14
sector 36a                                                    13
sector 46                                                     13
laxman vihar phase 2                                          13
sector 38                                                     12
sector 39                                                     12
sector 31                                                     12
sector 50                                                     12
sector 93                                                     12
uppals southend                                               12
sohna road                                                    12
sector 47                                                     11
sector 9a                                                     11
ashok vihar phase 3 extension                                 11
sector 1a imt manesar                                         10
sector 7                                                      10
sector 95a                                                     9
south city 1                                                   9
sector 55                                                      9
ashok vihar phase 2                                            9
sector 4                                                       9
sector 10a                                                     8
sector 40                                                      8
sector 59                                                      8
dwarka expressway                                              8
sector 57                                                      8
sector 89 a                                                    8
malibu town                                                    8
c block sushant lok phase 1                                    8
mehrauli  road                                                 8
palam vihar extension                                          8
sector 43                                                      8
new colony                                                     7
mianwali colony                                                7
sector 51                                                      7
sector 11                                                      7
sector 36 sohna                                                7
sector 26                                                      7
surat nagar 1                                                  7
sector 58                                                      7
ashok vihar                                                    6
sector 1                                                       6
sector 5                                                       6
jacobpura                                                      6
rajiv nagar                                                    6
jyoti park                                                     6
arjun nagar                                                    5
dayanand colony                                                5
manesar                                                        5
sector 80                                                      5
sector 28                                                      5
sushant lok phase 2                                            5
chakkarpur                                                     5
sector 2                                                       5
new palam vihar                                                5
sector 23a                                                     5
subhash nagar                                                  5
sector 30                                                      5
greenwood city                                                 5
sector 9                                                       5
ansal plaza                                                    5
sector 105                                                     5
saraswati vihar                                                5
dharam colony                                                  4
sector 45                                                      4
bhim nagar                                                     4
shivaji nagar                                                  4
sector 36                                                      4
sector 3a                                                      4
adarsh nagar                                                   4
devilal colony                                                 4
garhi harsaru                                                  4
bhondsi                                                        4
sector 12a                                                     4
imt manesar                                                    4
sector 12                                                      4
sector 17                                                      4
sector 6                                                       4
suncity                                                        4
surya vihar                                                    4
shivpuri                                                       4
vishnu garden                                                  4
ravi nagar                                                     4
baldev nagar                                                   4
valley view estate                                             4
new                                                            4
krishna colony                                                 4
madanpuri                                                      4
laxmi garden                                                   3
sector 15                                                      3
sector 23                                                      3
gandhi nagar                                                   3
sector 27                                                      3
sector 88b                                                     3
sector 110 a                                                   3
patel nagar                                                    3
a block sushant lok phase 1                                    3
sector 17a                                                     3
prem nagar                                                     3
sector 17b                                                     3
mg road                                                        3
shakti nagar                                                   3
sector 73                                                      3
maruti kunj                                                    3
sector 8                                                       3
b block sushant lok phase 1                                    3
faridabad road                                                 2
sector 32                                                      2
nars                                                           2
surat nagar                                                    2
hira nagar                                                     2
sector-2 sohna                                                 2
mohan nagar                                                    2
sector 21                                                      2
ambience island                                                2
sector 15 part 1                                               2
sector 15 part 2                                               2
daulatabad                                                     2
rajiv chowk                                                    2
, delhi ncr                                                    2
shanti nagar                                                   2
sector-11 sohna                                                2
bissar                                                         2
golf course road                                               2
sispal vihar                                                   2
surat nagar phase 2                                            2
rosewood                                                       2
bhawani enclave                                                2
golf course ext road                                           2
sector 41                                                      2
new basti                                                      2
pratap nagar                                                   2
farukhnagar                                                    2
west rajiv nagar                                               2
shankar vihar                                                  2
iffco chowk                                                    2
manohar nagar                                                  2
new palam vihar phase 2                                        2
sector 24                                                      2
acharya puri                                                   2
lajpat nagar                                                   2
new palam vihar phase 1                                        2
sohna  road                                                    2
sushant lok                                                    2
samaspur                                                       2
sheetla colony                                                 2
mayfield garden                                                2
block a surya vihar                                            2
naharpur rupa                                                  1
sector 5 chowk                                                 1
sector-5 sheetla colony                                        1
nirvana country pocket h                                       1
ansal's palam vihar                                            1
gopal nagar, garhi ghasita, sonipat                            1
khandsa                                                        1
near khandsa road                                              1
ashok vihar phase i                                            1
heritage city                                                  1
near nand hospital                                             1
ravi nager basai road                                          1
kheri                                                          1
om nagar                                                       1
cyber city                                                     1
bptp                                                           1
begampur khatola                                               1
kanahi                                                         1
tekchand nagar                                                 1
sector 42                                                      1
damdma                                                         1
carterpuri village                                             1
part 3 sector 5                                                1
pataudi road                                                   1
rattan garden                                                  1
sultanpur                                                      1
hsiidc plot sector 1 imt manesar                               1
mahavir pura                                                   1
sector 21a faridabad                                           1
old delhi road, opp sector-14                                  1
mahalaxmi garden, rajendra place                               1
saraswati enclave                                              1
g block dlf city phase 1                                       1
laxmna vihar, phase 2                                          1
sector-5 sohna                                                 1
b1 block sector 57                                             1
saroop garden rajendra park                                    1
rajiv colony                                                   1
huda saraswati vihar                                           1
godrej aria , sector 79 ,                                      1
dhankot                                                        1
devi lal colony gali no 12 gurgaon nr omkar public school      1
sector-35 sohna                                                1
near sector 1 market                                           1
hno 13 sagar enclave sura                                      1
south city                                                     1
sector 9b                                                      1
sector 17c                                                     1
ashok vihar phase 3                                            1
new jyoti park                                                 1
park view                                                      1
ats marigold                                                   1
shivji park colony                                             1
sector 13                                                      1
anand garden, sector-105                                       1
bhora kalan                                                    1
sector 37a                                                     1
near pataudi chowk                                             1
udyog vihar phase 1                                            1
bhimgarh kheri phase 3                                         1
garauli kalan                                                  1
block g sector-57                                              1
civil l                                                        1
lucknow                                                        1
laxman vihar, railway road,                                    1
block h ashok vihar phase iii extension                        1
sadar bazar                                                    1
sector-7 hous                                                  1
ram nagar                                                      1
sector 4 urban estate                                          1
sec 3 bhim vihar part 1 bhimgher kheri                         1
vir nagar                                                      1
sector 37b                                                     1
urban estate, sector 5                                         1
alipur                                                         1
sai kunj                                                       1
jat colony,fazilpur/taj nagar road                             1
new colony, sector 7                                           1
jacobpura near sadar bazar                                     1
near euro                                                      1
v block dlf phase 3                                            1
Name: sector, dtype: int64

In [15]:
df['sector'] = df['sector'].str.replace('dharam colony','sector 12')
df['sector'] = df['sector'].str.replace('krishna colony','sector 7')
df['sector'] = df['sector'].str.replace('suncity','sector 54')
df['sector'] = df['sector'].str.replace('prem nagar','sector 13')
df['sector'] = df['sector'].str.replace('mg road','sector 28')
df['sector'] = df['sector'].str.replace('gandhi nagar','sector 28')
df['sector'] = df['sector'].str.replace('laxmi garden','sector 11')
df['sector'] = df['sector'].str.replace('shakti nagar','sector 11')

In [16]:
df['sector'] = df['sector'].str.replace('baldev nagar','sector 7')
df['sector'] = df['sector'].str.replace('shivpuri','sector 7')
df['sector'] = df['sector'].str.replace('garhi harsaru','sector 17')
df['sector'] = df['sector'].str.replace('imt manesar','manesar')
df['sector'] = df['sector'].str.replace('adarsh nagar','sector 12')
df['sector'] = df['sector'].str.replace('shivaji nagar','sector 11')
df['sector'] = df['sector'].str.replace('bhim nagar','sector 6')
df['sector'] = df['sector'].str.replace('madanpuri','sector 7')

In [17]:
df['sector'] = df['sector'].str.replace('saraswati vihar','sector 28')
df['sector'] = df['sector'].str.replace('arjun nagar','sector 8')
df['sector'] = df['sector'].str.replace('ravi nagar','sector 9')
df['sector'] = df['sector'].str.replace('vishnu garden','sector 105')
df['sector'] = df['sector'].str.replace('bhondsi','sector 11')
df['sector'] = df['sector'].str.replace('surya vihar','sector 21')
df['sector'] = df['sector'].str.replace('devilal colony','sector 9')
df['sector'] = df['sector'].str.replace('valley view estate','gwal pahari')

In [18]:
df['sector'] = df['sector'].str.replace('mehrauli  road','sector 14')
df['sector'] = df['sector'].str.replace('jyoti park','sector 7')
df['sector'] = df['sector'].str.replace('ansal plaza','sector 23')
df['sector'] = df['sector'].str.replace('dayanand colony','sector 6')
df['sector'] = df['sector'].str.replace('sushant lok phase 2','sector 55')
df['sector'] = df['sector'].str.replace('chakkarpur','sector 28')
df['sector'] = df['sector'].str.replace('greenwood city','sector 45')
df['sector'] = df['sector'].str.replace('subhash nagar','sector 12')

In [19]:
df['sector'] = df['sector'].str.replace('sohna road road','sohna road')
df['sector'] = df['sector'].str.replace('malibu town','sector 47')
df['sector'] = df['sector'].str.replace('surat nagar 1','sector 104')
df['sector'] = df['sector'].str.replace('new colony','sector 7')
df['sector'] = df['sector'].str.replace('mianwali colony','sector 12')
df['sector'] = df['sector'].str.replace('jacobpura','sector 12')
df['sector'] = df['sector'].str.replace('rajiv nagar','sector 13')
df['sector'] = df['sector'].str.replace('ashok vihar','sector 3')

In [20]:
df['sector'] = df['sector'].str.replace('dlf phase 1','sector 26')
df['sector'] = df['sector'].str.replace('nirvana country','sector 50')
df['sector'] = df['sector'].str.replace('palam vihar','sector 2')
df['sector'] = df['sector'].str.replace('dlf phase 2','sector 25')
df['sector'] = df['sector'].str.replace('sushant lok phase 1','sector 43')
df['sector'] = df['sector'].str.replace('laxman vihar','sector 4')
df['sector'] = df['sector'].str.replace('dlf phase 4','sector 28')
df['sector'] = df['sector'].str.replace('dlf phase 3','sector 24')

In [21]:
df['sector'] = df['sector'].str.replace('sushant lok phase 3','sector 57')
df['sector'] = df['sector'].str.replace('dlf phase 5','sector 43')
df['sector'] = df['sector'].str.replace('rajendra park','sector 105')
df['sector'] = df['sector'].str.replace('uppals southend','sector 49')
df['sector'] = df['sector'].str.replace('sohna','sohna road')
df['sector'] = df['sector'].str.replace('ashok vihar phase 3 extension','sector 5')
df['sector'] = df['sector'].str.replace('south city 1','sector 41')
df['sector'] = df['sector'].str.replace('ashok vihar phase 2','sector 5')

In [22]:
a = df['sector'].value_counts()[df['sector'].value_counts() >= 3]
df = df[df['sector'].isin(a.index)]

In [23]:
df['sector'].value_counts()

sohna road                    163
sector 102                    113
sector 85                     110
sector 92                     104
sector 69                      94
sector 65                      90
sector 81                      90
sector 90                      90
sector 109                     88
sector 79                      80
sector 104                     73
sector 83                      69
sector 37d                     68
sector 86                      67
sector 50                      65
sector 107                     60
sector 108                     59
sector 56                      57
sector 95                      57
sector 89                      56
sector 48                      56
sector 2                       55
sector 70a                     54
sector 70                      53
sector 37c                     53
sector 43                      53
sector 84                      51
sector-33 sohna road           51
sector 26                      50
sector 67                      48
sector 49                      48
sector 28                      47
sector 66                      46
sector 103                     45
sector 113                     43
sector 25                      43
sector 61                      42
sector 82                      42
sector 7                       39
sector 106                     38
sector 4                       36
sector 99a                     32
sector 54                      31
sector 68                      30
sector 12                      30
sector 72                      29
sector 77                      29
sector 71                      27
sector 112                     24
sector 57                      24
sector 24                      24
sector 33                      23
sector 105                     23
sector 88a                     23
sector 14                      23
sector 67a                     22
sector 111                     22
sector 11                      21
sector 3                       20
sector 22                      20
sector 82a                     20
sector 78                      19
sector 47                      19
gwal pahari                    18
sector 74                      18
sector 63a                     18
sector 91                      17
sector 62                      17
sector 110                     16
sector 99                      16
sector 63                      15
sector 60                      15
sector 1 manesar               14
sector 52                      14
sector 55                      14
sector 53                      14
sector 76                      14
sector 4 phase 2               13
sector 46                      13
sector 9                       13
sector 6                       13
sector 36a                     13
sector 31                      12
sector 38                      12
sector 39                      12
sector 93                      12
sohna road road                12
sector 41                      11
sector 9a                      11
sector 3 phase 3 extension     11
sector 1a manesar              10
sector 13                      10
sector 95a                      9
manesar                         9
sector 45                       9
sector 3 phase 2                9
c block sector 43               8
sector 89 a                     8
sector 2 extension              8
sector 8                        8
dwarka expressway               8
sector 17                       8
sector 59                       8
sector 23                       8
sector 10a                      8
sector 40                       8
sector 51                       7
sector 36 sohna road            7
sector 58                       7
sector 5                        6
sector 1                        6
sector 21                       6
sector 30                       5
new sector 2                    5
sector 80                       5
sector 23a                      5
sector 36                       4
sector 12a                      4
sector 3a                       4
new                             4
sector 73                       3
sector 17b                      3
sector 110 a                    3
b block sector 43               3
sector 17a                      3
patel nagar                     3
sector 88b                      3
sector 27                       3
sector 15                       3
a block sector 43               3
maruti kunj                     3
Name: sector, dtype: int64

In [24]:
df['sector'] = df['sector'].str.replace('sector 95a','sector 95')
df['sector'] = df['sector'].str.replace('sector 23a','sector 23')
df['sector'] = df['sector'].str.replace('sector 12a','sector 12')
df['sector'] = df['sector'].str.replace('sector 3a','sector 3')
df['sector'] = df['sector'].str.replace('sector 110 a','sector 110')
df['sector'] = df['sector'].str.replace('patel nagar','sector 15')
df['sector'] = df['sector'].str.replace('a block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('maruti kunj','sector 12')
df['sector'] = df['sector'].str.replace('b block sector 43','sector 43')

In [25]:
df['sector'] = df['sector'].str.replace('sector-33 sohna road','sector 33')
df['sector'] = df['sector'].str.replace('sector 1 manesar','manesar')
df['sector'] = df['sector'].str.replace('sector 4 phase 2','sector 4')
df['sector'] = df['sector'].str.replace('sector 1a manesar','manesar')
df['sector'] = df['sector'].str.replace('c block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('sector 89 a','sector 89')
df['sector'] = df['sector'].str.replace('sector 2 extension','sector 2')
df['sector'] = df['sector'].str.replace('sector 36 sohna road','sector 36')

In [26]:
df[df['sector'] == 'new']

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
134,4 BHK Flat in New Gurgaon,flat,sare homes,new,0.85,4786.0,1776.0,Super Built up area 1776(165 sq.m.),4,4,3,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,5 to 10 Year Old,"['Columbia Asia Hospital', 'Apex Multi Special...",Located in the popular residential address of ...,[],NaN,NaN
1631,2 BHK Flat in New Gurgaon,flat,takshila heights sector 37 c,new,0.67,5583.0,1200.0,Super Built up area 1200(111.48 sq.m.),2,2,2,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,1 to 5 Year Old,"['Shri Balaji Hospital and Trauma Center', 'S....",Check out this 2 bhk apartment for sale in tak...,[],"['Lift(s)', 'Swimming Pool', 'Visitor Parking'...",NaN
2120,2 BHK Flat in New Gurgaon,flat,green court,new,0.38,5507.0,690.0,Carpet area: 690 (64.1 sq.m.),2,2,1,not available,"New Gurgaon, Gurgaon, Haryana",7.0,NaN,Under Construction,"['Ing bank ATM', 'Dcb bank ATM', 'Indus ind ba...",We are the proud owners of this 2 bhk apartmen...,[],"['Intercom Facility', 'Lift(s)', 'Maintenance ...",NaN
3520,4 BHK Flat in New Gurgaon,flat,dlf 76,new,4.00,11428.0,3500.0,Carpet area: 3500 (325.16 sq.m.),4,4,2,"study room,servant room","New Gurgaon, Gurgaon, Haryana",4.0,NaN,Jun 2027,"['Shri Balaji Hospital and Trauma Center', 'S....",This lovely 4 bhk apartment/flat in new gurgao...,"['6 Wardrobe', '1 Fridge', '8 Fan', '1 Exhaust...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",NaN

In [29]:
df.loc[955]

property_name                        1 BHK Flat in Sector 56 Gurgaon
property_type                                                   flat
society                                             smriti apartment
sector                                                     sector 37
price                                                           0.52
price_per_sqft                                               10666.0
area                                                           488.0
areaWithType                    Super Built up area 525(48.77 sq.m.)
bedRoom                                                          1.0
bathroom                                                         1.0
balcony                                                            1
additionalRoom                                         not available
address            D101 Smriti Apartment, Sector 56 Gurgaon, Gurg...
floorNum                                                         1.0
facing                                                           NaN
agePossession                                           10+ Year Old
nearbyLocations    ['Sector 54 chowk metro station', 'Sector metr...
description        Corner property sample flat of the society. Lo...
furnishDetails     ['2 Fan', '3 Light', '1 Wardrobe', 'No AC', 'N...
features           ['Feng Shui / Vaastu Compliant', 'Maintenance ...
rating             ['Safety4 out of 5', 'Lifestyle5 out of 5', 'E...
Name: 955, dtype: object

In [28]:
df.loc[955,'sector'] = 'sector 37'
df.loc[2800,'sector'] = 'sector 92'
df.loc[2838,'sector'] = 'sector 90'
df.loc[2857,'sector'] = 'sector 76'

In [30]:
df[df['sector'] == 'new sector 2']

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
1127,3 Bedroom House for sale in New Palam Vihar,house,independent,new sector 2,1.00,8796.0,1137.0,Plot area 120(100.34 sq.m.)Built Up area: 120 ...,3.0,2.0,2,pooja room,"Q-148, New Palam Vihar, Phase-2, Near Royal Oa...",1.0,North,10+ Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","Ground and first floor, Ground floor: Ground f...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
1602,2 BHK Flat in New Palam Vihar,flat,my home,new sector 2,0.28,3166.0,884.0,Carpet area: 900 (83.61 sq.m.),2.0,1.0,1,others,"F 150/b, New Palam Vihar, Gurgaon, Haryana",2.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","2 bhk room with wooden coverd ,1 drawing room,...","['3 Wardrobe', '5 Light', '1 Chimney', '1 Modu...","['Water Storage', 'Park']","['Environment4 out of 5', 'Safety4 out of 5', ..."
2187,2 BHK Flat in New Palam Vihar,flat,ompee k s residency,new sector 2,1.60,26936.0,594.0,Carpet area: 66 (55.18 sq.m.),2.0,2.0,2,not available,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",We are the proud owners of this 2 bhk apartmen...,NaN,NaN,"['Environment4 out of 5', 'Safety4 out of 5', ..."
3155,2 Bedroom House for sale in New Palam Vihar,house,my home,new sector 2,0.34,12592.0,270.0,Plot area 270(25.08 sq.m.),2.0,2.0,2,not available,"Ez-19 A, New Palam Vihar, Gurgaon, Haryana",3.0,West,5 to 10 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",There are availability of various facilities l...,"['1 Wardrobe', '3 Fan', '6 Light', 'No AC', 'N...","['Water Storage', 'Park', 'Visitor Parking']","['Environment4 out of 5', 'Lifestyle4 out of 5..."
3539,2 BHK Flat in New Palam Vihar,flat,my home,new sector 2,0.22,4400.0,500.0,Carpet area: 500 (46.45 sq.m.),2.0,2.0,1,not available,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,0 to 1 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",Cctv surveillance are provided here. There is ...,"['3 Fan', '1 Exhaust Fan', '15 Light', '1 Modu...",NaN,"['Safety4 out of 5', 'Lifestyle4 out of 5', 'E..."

In [31]:
df.loc[[311,1072,1486,3040,3875],'sector'] = 'sector 110'

In [32]:
df.shape

(3804, 21)

In [33]:
df.duplicated().sum()

0

In [34]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Sohna,flat,ashiana anmol,sohna road,0.88,11125.0,791.0,Super Built up area 1275(118.45 sq.m.)Carpet a...,2.0,2.0,2,not available,"Sohna, Gurgaon, Haryana",13.0,East,1 to 5 Year Old,"['Global Signum Plaza', 'Airia Mall', 'Sohna R...",Fully furnished flat with southfacing balconie...,"['1 Water Purifier', '4 Fan', '1 Exhaust Fan',...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area4 out of 5', 'Amenities4 out of 5'..."
1,3 BHK Flat in Sector 70 Gurgaon,flat,shree vardhman victoria,sector 70,1.65,8461.0,1950.0,Super Built up area 1950(181.16 sq.m.)Carpet a...,3.0,4.0,3,servant room,"Sector 70 Gurgaon, Gurgaon, Haryana",1.0,North,1 to 5 Year Old,"['Airia Mall', 'Golf Course Extn Road', 'Sohna...",Victoria is a perfect residential complex from...,"['1 Water Purifier', '4 Fan', '1 Fridge', '1 D...","['Water purifier', 'Centrally Air Conditioned'...","['Green Area5 out of 5', 'Construction5 out of..."
2,3 BHK Flat in Sector 37D Gurgaon,flat,bptp terra,sector 37d,1.45,8006.0,1811.0,Super Built up area 1811(168.25 sq.m.)Built Up...,3.0,3.0,3,not available,"803, Sector 37D Gurgaon, Gurgaon, Haryana",8.0,South-East,1 to 5 Year Old,"['Airia Mall', 'Dwarka Expressway', 'Golf Cour...",This lovely 3 bhk apartment/flat in sector 37d...,"['5 AC', '1 Chimney', '1 Modular Kitchen', '2 ...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area4.5 out of 5', 'Construction4.5 ou..."
3,3 BHK Flat in Sector 72 Gurgaon,flat,tata primanti,sector 72,3.30,15384.0,2145.0,Super Built up area 2145(199.28 sq.m.)Built Up...,3.0,3.0,3+,servant room,"1001, Sector 72 Gurgaon, Gurgaon, Haryana",10.0,North-East,1 to 5 Year Old,"['Sector 55-56 Metro Station', 'Omaxe City Cen...",Check out this 3 bhk apartment for sale in tat...,"['3 Wardrobe', '7 Fan', '1 Exhaust Fan', '4 Ge...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area4 out of 5', 'Construction4 out of..."
4,2 BHK Flat in Sector 107 Gurgaon,flat,signature global solera,sector 107,0.28,5828.0,480.0,Carpet area: 489 (45.43 sq.m.),2.0,2.0,2,not available,"Sector 107 Gurgaon, Gurgaon, Haryana",0.0,North-East,1 to 5 Year Old,"['Gurgaon Dreamz Mall', 'Dwarka Expressway', ""...",This lovely 2 bhk apartment/flat in sector-107...,"['1 Wardrobe', '2 Fan', '1 Exhaust Fan', '2 Li...","['Security / Fire Alarm', 'Intercom Facility',...","['Green Area4.5 out of 5', 'Construction4.5 ou..."

In [35]:
# features to drop -> property_name, address, description, rating
df.drop(columns=['property_name', 'address', 'description', 'rating'],inplace=True)

In [36]:
df.sample(5)

,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,floorNum,facing,agePossession,nearbyLocations,furnishDetails,features
949,house,ats tourmaline,sector 109,1.87,8697.0,2150.0,Built Up area: 2150 (199.74 sq.m.),3.0,4.0,0,not available,12.0,NaN,undefined,"['Dwarka Sector 21 Metro Station', 'NeoSquare ...",NaN,NaN
1159,flat,godrej nature plus,sector 33,1.08,13126.0,823.0,Carpet area: 76.44,2.0,2.0,3,not available,8.0,NaN,Jan 2024,"['Signature Global Infinity Mall Sohna', 'Bads...",NaN,NaN
2474,flat,dlf garden city floors,sector 92,1.70,8588.0,1980.0,Super Built up area 1630(151.43 sq.m.),3.0,4.0,2,not available,1.0,NaN,Dec 2024,"['Sapphire 83 Mall', 'Dwarka Expressway', 'NH-...",[],NaN
1188,flat,emaar mgf the palm drive,sector 66,4.60,18400.0,2500.0,Super Built up area 3300(306.58 sq.m.)Carpet a...,3.0,3.0,3,"pooja room,study room,servant room,store room",11.0,North,1 to 5 Year Old,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","['1 Stove', '5 AC', '1 Modular Kitchen', '1 Ch...","['Water purifier', 'Security / Fire Alarm', 'F..."
2088,house,international city by sobha phase 2,sector 109,11.25,25000.0,4500.0,Plot area 500(418.06 sq.m.),7.0,5.0,3+,"pooja room,study room,servant room",4.0,North-East,1 to 5 Year Old,"['Dwarka Sector 21 Metro Station', 'Pacific D2...",NaN,"['Feng Shui / Vaastu Compliant', 'Private Gard..."

In [37]:
# feature engineering required -> areaWithType, additionalRoom, facing, agePossession, furnishDetails, features

In [38]:
df.duplicated().sum()

120

In [39]:
df.to_csv('gurgaon_properties_cleaned_v1.csv',index=False)